services:
  my-nginx-service:
    image: nginx:latest
  web:
    image: kelvinquida24/rk8s-py:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "kelvinquida24/rk8s-py:${TAG:-latest}"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - mywebdata:/app/data
  my-redis-service:
    image: redis:latest
    volumes:
      - myredisdata:/data

volumes:
  mywebdata:
  myredisdata:
